### ISSUE TITLE
[Feature Request] allow customized query function

### ISSUE THREAD

**Issue by uu-z** [remult/remult#389]
**Is your feature request related to a problem? Please describe.**
I wanna customize query functions like `findOne` `findFirst` to add cahe  to improve api performance.

**Describe the solution you'd like**
enable the ability to modify the result of`findFirst` `findOne` ...
<img width="665" alt="image" src="https://github.com/remult/remult/assets/12439992/e1d242fa-877d-4372-87cc-37baeab53298">

**Additional context**
it's also very useful if we could modify the API response header like `cache-control`
<img width="589" alt="image" src="https://github.com/remult/remult/assets/12439992/26e543b4-dab5-41a4-a5cc-7db52397866b">

**Comment by noam-honig** [comment]
Hi, @uu-z, I think that the best way to achieve this is by implementing decorated data provider (wrapping the real data provider, with a data provider that gets the data from cache etc...)

You can use the `remult.context` object and customize it according to the following article to achieve the header setting functionality:
https://remult.dev/docs/custom-options.html#augmenting-remult-s-context-property

And you can set the header in the allowApiRead implementation

Would you like an example?

**Comment by uu-z** [comment]
> Hi, @uu-z, I think that the best way to achieve this is by implementing decorated data provider (wrapping the real data provider, with a data provider that gets the data from cache etc...)
> 
> You can use the `remult.context` object and customize it according to the following article to achieve the header setting functionality: https://remult.dev/docs/custom-options.html#augmenting-remult-s-context-property
> 
> And you can set the header in the allowApiRead implementation
> 
> Would you like an example?
Hi @noam-honig, it's great, I will give it a try! 
also, it would be useful if you could provide an example, thanks!!!

**Comment by noam-honig** [comment]
Ok - see:
https://stackblitz.com/~/github.com/remult/react-vite-express-starter

To demo the caching behaviour - I created a file called `DataProviderWrapper.ts` that has a data provider that caches in a dictionary resutls by ids.

It's bare but I would use that as a starting point for your implementation.

To set the header - it required a bit more twisting, since remult's api doesn't include the response object.

So - I used the types.d.ts file to add `setHeader` method to both express's `Request` object, and to remult's context object.

In the index.ts - I've set the requests setHeader method - to call the response.header method.

In the api.ts - I've set that method to the remult.context.setHeader method.

And in the task.ts - in the allow Api read, I've used it.

try it out

**Comment by uu-z** [comment]
@noam-honig looks good, but I can't find the file you mentioned in this example project, it seems that the code hasn't been updated, could you please check the link?  Thank you.

**Comment by noam-honig** [comment]
Hi - Sorry about that, I'm in transition from codesandbox to stackblitz - and I thought that if I click share it shares :)

Checkout this code sandbox:
https://codesandbox.io/p/devbox/github/noam-honig/react-vite-express-starter/tree/noam-honig%2Fdemo-wrap-data-provider/

try navigating to /api/tasks - you'll see in the network tab that a header called "noam" was added to the response.

Try navigating to /api/tasks/ui9dtyo6q3v4r6z6pkcdjdzo - you'll see in the terminal that it added that id to the cache - any next call will be returned for the cache
![image](https://github.com/remult/remult/assets/16635859/545468fe-4d0d-4584-a189-5ea236b0e959)


Here's my previous comments - but with screen shots now :)


To demo the caching behavior - I created a file called DataProviderWrapper.ts that has a data provider that caches in a dictionary results by ids.
https://github.com/noam-honig/react-vite-express-starter/blob/noam-honig/demo-wrap-data-provider/src/server/DataProviderWrapper.ts

It's bare but I would use that as a starting point for your implementation.

To set the header - it required a bit more twisting, since remult's api doesn't include the response object.

So - I used the types.d.ts file to add setHeader method to both express's Request object, and to remult's context object.
https://github.com/noam-honig/react-vite-express-starter/blob/noam-honig/demo-wrap-data-provider/src/shared/types.d.ts
![image](https://github.com/remult/remult/assets/16635859/7238aec2-cf78-42f2-b3a1-5048910f2458)



In the index.ts - I've set the requests setHeader method - to call the response.header method.

https://github.com/noam-honig/react-vite-express-starter/blob/noam-honig/demo-wrap-data-provider/src/server/index.ts#L7-L10
![image](https://github.com/remult/remult/assets/16635859/42050267-ac8a-4afc-80df-1ea4c569564a)


In the api.ts - I've set that method to the remult.context.setHeader method.
https://github.com/noam-honig/react-vite-express-starter/blob/noam-honig/demo-wrap-data-provider/src/server/api.ts#L10-L12
![image](https://github.com/remult/remult/assets/16635859/aa10c036-fbec-4da1-880a-55d3e013f7aa)


And in the task.ts - in the allow Api read, I've used it.
https://github.com/noam-honig/react-vite-express-starter/blob/noam-honig/demo-wrap-data-provider/src/shared/tasks.ts#L3-L9
![image](https://github.com/remult/remult/assets/16635859/f814c1c1-7486-4ffa-b498-801dc7690ca3)



Let me know

**Comment by uu-z** [comment]
awesome, thanks for the great example.

**Comment by noam-honig** [comment]
I've also rewritten the [Extensibility](https://remult.dev/docs/custom-options.html) article based on this discussion
