### ISSUE TITLE
Async authorisation

### ISSUE THREAD

**Issue by konall** [remult/remult#486]
Hi there! Thanks for this great project, it's been great to use thus far!

**Is your feature request related to a problem? Please describe.**
I would like to authenticate my db access based on the user's relationship to certain entities, which requires me to make a db access in the `allowApiCrud` callback- however, the callback cannot currently return a Promise, which I would require to await the result of my db access.

**Describe the solution you'd like**
I'm not familiar with the internals of the project, but if it wouldn't cause a major breakage then allowing an `allowApiCrud` callback to be async would be ideal.

**Describe alternatives you've considered**
I have come across the `apiPreprocessFilter` option which does allow for an async callback, however if I'm interpreting correctly it doesn't seem to be a perfect/simplest encapsulation of the intent of my authentication logic, and also doesn't allow my frontend to leverage the `repo.metadata.apiXxxAllowed()` functionality, which would be a pity.

**Additional context**
None! Thanks again for the great project!

**Comment by noam-honig** [comment]
Hi @konall, 

Turning the `allowApiCrud` to `async` will hinder the ability of using the in the frontend in render, since render is never async.

I use `apiPrefilter` and `apiPrprocessFilter` for this functionality in my projects.

Sometimes I extend the `UserInfo` object with relevant information for these rules on sign in, and use that in the `allowApiCrud` - for example companies that this user is an admin in - that way that information is available both in front and backend.

If you want we can review together an example on stackblitz or similar and dive deeper into this discussion.

Also - tomorrow we have "office hours" where anyone can join a live discussion with the authors of remult, you can join at:
https://discord.gg/VRQCgkGs?event=1280422150049632320

**Comment by konall** [comment]
Thanks for your quick response and advice! Using `apiPrefilter` should be ok for me, but I'm just wondering if I can determine which CRUD operation is being performed from within that callback? Or do I just have to split my authentication across `apiPrefilter`, `saving` (+ e.isNew) and `deleting`?
Thanks!

**Comment by noam-honig** [comment]
Hi @konall 
apiPrefilter also applies to update and delete, since you can't delete or update a row your not allowed to read.

If you want more fine grained solution for new vs existing vs deleting then yes, you need to apply it in the respective events.

Good enough?
