### ISSUE TITLE
Let AllowedForInstance depend on related entities

### ISSUE THREAD

**Issue by groszdaniel** [remult/remult#528]
**Is your feature request related to a problem? Please describe.**
Our project has various entities representing "children" of other entities, a typical many-to-one relation from the child to the parent. A user's permissions to a child entity are mostly determined by its permissions to the parent entity, so we need to look at the parent entity in the "allowed" functions. However, with the new style relations (`@Relations.toOne()` etc.) we can't do that because the AllowedForInstance functions can't be async, and related entities aren't loaded in the entity passed to them (even if specified with defaultIncluded).

**Describe the solution you'd like**
The most natural solution would be to let Allowed/AllowedForInstance functions be async. A lot of asynchronous stuff happens around that stage anyway (such as loading the entity itself from the database, evaluating any serverExpressions).

Also, it appears that related entities aren't included in the entity passed to the allowedForInstance function even when they are specified with defaultIncluded. If they were, that would be another solution. I don't know if that's intentional that they aren't; on the one hand it looks like a bug, on the other, if they were included, it would be impossible to optimize performance by avoiding loading them, since there is no place to customize which relations the allowedForInstance wants to be loaded.

**Describe alternatives you've considered**
Old style relations (`@Field(() => ...)`) are loaded in the entity passed to the allowed function. However, new style relations are more convenient in some ways. I've also started running into a bug with old style relations. (With PostgreSQL+Knex, if a backend method that runs in a transaction calls a find() query with the load: option specifying that some old style relations shouldn't be loaded—which we need to avoid circular loading infinite loops with serverExpressions loading corresponding one-to-many relations—, in some cases we get "Error: Transaction query already complete, run with DEBUG=knex:tx for more info" errors. I haven't yet been able to reproduce it with a simple sample project to report it, and I don't even know if old style relations are supposed to be maintained anyway; I didn't get this error with new style relations and the include: option.)

I think we could work around the problem that allowed functions can't be async by writing serverExpressions that load the related (parent) entities from the database, since those _can_ be async, but it would be an otherwise pointless duplication.

**Comment by noam-honig** [comment]
Hi @groszdaniel,

Most of the allowedForInstance method are used also as part of rendering in react and as such can't be async. (allowApiDelete to show/hide a button)

There a different strategies that you can take:
If you need to filter rows - hide rows from the user based on async rules, the best way to do that is with apiPrefilter - which is async.

The approach you've mentioned using `serverExpression` is also good, it'll have the benefit of caching the result and using it in multiple fields. you can also resuse the relations there, by loading them using the `await getEntityRef(item).fields.waitLoad()`

Another approach that I use a lot (for multi tenant scenarios) is store the allowed environments either on the user object or the `remult.context` object - init it in the initRequest and than it's available throughout the code.

In reality - for my projects, I would prefer to use sqlExpression instead of serverExpression - to have the "calculation" run as part of the original query - for improved performance - and we're creating helper methods to make that part easier.

See if this helps - and if not, I would love to work with an example we can both look at and consider alternatives.

You can use this stackblitz project as a starting point
https://stackblitz.com/github/noam-honig/ready-to-play
or
https://stackblitz.com/github/remult/remult/tree/main/examples/groupBy?file=src%2Ffrontend%2Fpage.tsx
that already have a relation in it

Let me know what you think

**Comment by noam-honig** [comment]
One more thing - regarding ""Error: Transaction query already complete, run with DEBUG=knex:tx for more info" "
that error happens when you're not waiting for a promise and a select statement get sent to the db after the transaction was comitted
